# ======================== НАСТРОЙКИ БД ========================
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#spring.datasource.url=jdbc:oracle:thin:@172.16.21.2:1521:DEVPLUS

spring.datasource.url=jdbc:oracle:thin:@172.16.21.45:1521:plusora
spring.datasource.username=prb
spring.datasource.password=rmn_ppb

spring.application.name=quality-controll-app

# ======================== JPA / HIBERNATE ========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Minsk
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
