# ======================== НАСТРОЙКИ БД ========================
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.url=jdbc:oracle:thin:@172.16.21.2:1521:DEVPLUS

spring.datasource.username=prb
spring.datasource.password=rmn_ppb

spring.application.name=quality-controll-app
