
CREATE TABLE PRODUCTION_REPORT (
    ID_PRODUCTION_REPORT NUMBER PRIMARY KEY,
    REPORT_DATE DATE NOT NULL,
    ID_PRODUCTION_SITE NUMBER NOT NULL,
    PRODUCED_WEIGHT_TONNES NUMBER(10,3) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50),
    CONSTRAINT FK_PRODUCTION_REPORT_SITE FOREIGN KEY (ID_PRODUCTION_SITE) REFERENCES PRODUCTION_SITE(ID_PRODUCTION_SITE)
);

-- Sequence для Primary Key
CREATE SEQUENCE SEQ_PRODUCTION_REPORT START WITH 1 INCREMENT BY 1;

CREATE INDEX IDX_PRODUCTION_REPORT_DATE ON PRODUCTION_REPORT(REPORT_DATE);

CREATE INDEX IDX_PRODUCTION_REPORT_SITE_DATE ON PRODUCTION_REPORT(ID_PRODUCTION_SITE, REPORT_DATE);
