SET PAGESIZE 50
SET LINESIZE 200


DESC HLP_DIAMETER;
/
DESC HLP_STEEL_GRADE;
/


SELECT '=== HLP_PRODUCTION_SITE ===' AS "" FROM DUAL;
SELECT * FROM HLP_PRODUCTION_SITE;
/

SELECT '=== HLP_DEFECT_TYPE ===' AS "" FROM DUAL;
SELECT * FROM HLP_DEFECT_TYPE;
/

SELECT '=== HLP_DETECTION_SOURCE ===' AS "" FROM DUAL;
SELECT * FROM HLP_DETECTION_SOURCE;
/

SELECT '=== HLP_REWORK_TYPE ===' AS "" FROM DUAL;
SELECT * FROM HLP_REWORK_TYPE;
/

SELECT '=== HLP_DIAMETER ===' AS "" FROM DUAL;
SELECT * FROM HLP_DIAMETER;
/

SELECT '=== HLP_STEEL_GRADE ===' AS "" FROM DUAL;
SELECT * FROM HLP_STEEL_GRADE;
/

SELECT '=== HLP_DEFECT_CAUSE ===' AS "" FROM DUAL;
SELECT ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE FROM HLP_DEFECT_CAUSE ORDER BY ID_DEFECT_CAUSE;
/
