
INSERT INTO HLP_PRODUCTION_SITE (ID_PRODUCTION_SITE, SITE_CODE, SITE_NAME, ALLOWABLE_DEFECT_PERCENT)
VALUES (1, 'СК', 'Склад катанки (СК)', 0.50);

INSERT INTO HLP_PRODUCTION_SITE (ID_PRODUCTION_SITE, SITE_CODE, SITE_NAME, ALLOWABLE_DEFECT_PERCENT)
VALUES (2, 'ТУ', 'Травильный участок (ТУ)', 0.10);

INSERT INTO HLP_PRODUCTION_SITE (ID_PRODUCTION_SITE, SITE_CODE, SITE_NAME, ALLOWABLE_DEFECT_PERCENT)
VALUES (3, 'ГСВ', 'Участок грубо-среднего волочения (ГСВ)', 0.10);

INSERT INTO HLP_PRODUCTION_SITE (ID_PRODUCTION_SITE, SITE_CODE, SITE_NAME, ALLOWABLE_DEFECT_PERCENT)
VALUES (4, 'ТТГУ', 'Термотравильно-гальванический участок (ТТГУ)', 0.25);

INSERT INTO HLP_PRODUCTION_SITE (ID_PRODUCTION_SITE, SITE_CODE, SITE_NAME, ALLOWABLE_DEFECT_PERCENT)
VALUES (5, 'УТВ-МК', 'Участок тонкого волочения (проволока под металлокорд)', 0.21);

INSERT INTO HLP_PRODUCTION_SITE (ID_PRODUCTION_SITE, SITE_CODE, SITE_NAME, ALLOWABLE_DEFECT_PERCENT)
VALUES (6, 'УТВ-РМЛ', 'Участок тонкого волочения (проволока РМЛ)', 0.29);

INSERT INTO HLP_PRODUCTION_SITE (ID_PRODUCTION_SITE, SITE_CODE, SITE_NAME, ALLOWABLE_DEFECT_PERCENT)
VALUES (7, 'УТВ-СВ', 'Участок тонкого волочения (сварочная проволока)', 0.30);

INSERT INTO HLP_PRODUCTION_SITE (ID_PRODUCTION_SITE, SITE_CODE, SITE_NAME, ALLOWABLE_DEFECT_PERCENT)
VALUES (8, 'КУ-1', 'Канатный участок №1 (КУ-1)', 0.58);

INSERT INTO HLP_PRODUCTION_SITE (ID_PRODUCTION_SITE, SITE_CODE, SITE_NAME, ALLOWABLE_DEFECT_PERCENT)
VALUES (9, 'КУ-2', 'Канатный участок №2 (КУ-2)', 0.72);

COMMIT;





INSERT INTO HLP_DEFECT_TYPE (ID_DEFECT_TYPE, DEFECT_CODE, DEFECT_NAME, IS_REWORKABLE)
VALUES (1, 'NM', 'Намот', 1);


INSERT INTO HLP_DEFECT_TYPE (ID_DEFECT_TYPE, DEFECT_CODE, DEFECT_NAME, IS_REWORKABLE)
VALUES (2, 'KR', 'Кольцо', 1);


INSERT INTO HLP_DEFECT_TYPE (ID_DEFECT_TYPE, DEFECT_CODE, DEFECT_NAME, IS_REWORKABLE)
VALUES (3, 'RS', 'Рев. скрутка', 1);


INSERT INTO HLP_DEFECT_TYPE (ID_DEFECT_TYPE, DEFECT_CODE, DEFECT_NAME, IS_REWORKABLE)
VALUES (4, 'NP', 'Непрямолинейность', 1);


INSERT INTO HLP_DEFECT_TYPE (ID_DEFECT_TYPE, DEFECT_CODE, DEFECT_NAME, IS_REWORKABLE)
VALUES (5, 'NP', 'Неровная поверхность', 1);


INSERT INTO HLP_DEFECT_TYPE (ID_DEFECT_TYPE, DEFECT_CODE, DEFECT_NAME, IS_REWORKABLE)
VALUES (6, 'NS', 'Некачественная свивка', 1);


INSERT INTO HLP_DEFECT_TYPE (ID_DEFECT_TYPE, DEFECT_CODE, DEFECT_NAME, IS_REWORKABLE)
VALUES (7, 'SK', 'Сбой в укладчике', 1);


INSERT INTO HLP_DEFECT_TYPE (ID_DEFECT_TYPE, DEFECT_CODE, DEFECT_NAME, IS_REWORKABLE)
VALUES (8, 'DK', 'Дефект покрытия', 1);


INSERT INTO HLP_DEFECT_TYPE (ID_DEFECT_TYPE, DEFECT_CODE, DEFECT_NAME, IS_REWORKABLE)
VALUES (9, 'DT', 'Дефект травления', 1);


INSERT INTO HLP_DEFECT_TYPE (ID_DEFECT_TYPE, DEFECT_CODE, DEFECT_NAME, IS_REWORKABLE)
VALUES (10, 'PS', 'Пересорт', 0);


INSERT INTO HLP_DEFECT_TYPE (ID_DEFECT_TYPE, DEFECT_CODE, DEFECT_NAME, IS_REWORKABLE)
VALUES (11, 'BR', 'Брак неисправимый', 0);


INSERT INTO HLP_DEFECT_TYPE (ID_DEFECT_TYPE, DEFECT_CODE, DEFECT_NAME, IS_REWORKABLE)
VALUES (12, 'IE', 'Износ оборудования', 1);

COMMIT;







INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (1, 'C01', 'Сбой в работе укладчика', NULL);


INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (11, 'C01-01', 'Выход из строя пиноли зажима', 1);

INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (12, 'C01-02', 'Износ ремня', 1);

INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (13, 'C01-03', 'Не установлена', 1);


INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (2, 'C02', 'Отсутствие контроля со стороны персонала', NULL);

INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (21, 'C02-01', 'Выдан ТП', NULL);


INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (3, 'C03', 'Разбило чистовую волоку', NULL);

INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (31, 'C03-01', 'Преждевременный износ волок', 3);


INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (4, 'C04', 'Износ роликов рихтовки', NULL);

INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (41, 'C04-01', 'Отсутствие резерва замены', 4);


INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (5, 'C05', 'Отсутствует запасная часть', NULL);


INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (6, 'C06', 'Технологический режим нарушен', NULL);

INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (61, 'C06-01', 'Невыдержанная температура', 6);

INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (62, 'C06-02', 'Нарушена скорость волочения', 6);


INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (7, 'C07', 'Несоответствие заготовки', NULL);

INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (71, 'C07-01', 'Несоответствие диаметра', 7);

INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (72, 'C07-02', 'Поверхность заготовки нечистая', 7);


INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (8, 'C08', 'Человеческий фактор', NULL);

INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (81, 'C08-01', 'Ошибочная установка параметров', 8);

INSERT INTO HLP_DEFECT_CAUSE (ID_DEFECT_CAUSE, CAUSE_CODE, CAUSE_NAME, ID_PARENT_CAUSE)
VALUES (82, 'C08-02', 'Неправильная сборка', 8);

COMMIT;




INSERT INTO HLP_DETECTION_SOURCE (ID_DETECTION_SOURCE, SOURCE_CODE, SOURCE_NAME)
VALUES (1, 'ОТК', 'ОТК');

INSERT INTO HLP_DETECTION_SOURCE (ID_DETECTION_SOURCE, SOURCE_CODE, SOURCE_NAME)
VALUES (2, 'ЦЕХ', 'Цех');

INSERT INTO HLP_DETECTION_SOURCE (ID_DETECTION_SOURCE, SOURCE_CODE, SOURCE_NAME)
VALUES (3, 'ЛИ', 'Линия контроля (ЛИ)');

INSERT INTO HLP_DETECTION_SOURCE (ID_DETECTION_SOURCE, SOURCE_CODE, SOURCE_NAME)
VALUES (4, 'ЦЗЛ', 'ЦЗЛ');

INSERT INTO HLP_DETECTION_SOURCE (ID_DETECTION_SOURCE, SOURCE_CODE, SOURCE_NAME)
VALUES (5, 'ВОЗВ', 'Возврат с последующего передела');

COMMIT;




INSERT INTO HLP_REWORK_TYPE (ID_REWORK_TYPE, REWORK_CODE, REWORK_NAME)
VALUES (1, 'RV', 'Восстановлено');

INSERT INTO HLP_REWORK_TYPE (ID_REWORK_TYPE, REWORK_CODE, REWORK_NAME)
VALUES (2, 'PN', 'Переназначено');

COMMIT;




INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (1, 0.10);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (2, 0.12);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (3, 0.14);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (4, 0.16);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (5, 0.18);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (6, 0.20);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (7, 0.22);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (8, 0.25);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (9, 0.28);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (10, 0.30);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (11, 0.35);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (12, 0.40);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (13, 0.50);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (14, 0.60);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (15, 0.80);
INSERT INTO HLP_DIAMETER (ID_DIAMETER, DIAMETER_VALUE) VALUES (16, 1.00);

COMMIT;




INSERT INTO HLP_STEEL_GRADE (ID_STEEL_GRADE, STEEL_CODE, STEEL_NAME) VALUES (1, '08ГФ', 'Сталь 08ГФ');
INSERT INTO HLP_STEEL_GRADE (ID_STEEL_GRADE, STEEL_CODE, STEEL_NAME) VALUES (2, '95Г2Ф', 'Сталь 95Г2Ф');
INSERT INTO HLP_STEEL_GRADE (ID_STEEL_GRADE, STEEL_CODE, STEEL_NAME) VALUES (3, '65Г', 'Сталь 65Г');
INSERT INTO HLP_STEEL_GRADE (ID_STEEL_GRADE, STEEL_CODE, STEEL_NAME) VALUES (4, '70Х', 'Сталь 70Х');
INSERT INTO HLP_STEEL_GRADE (ID_STEEL_GRADE, STEEL_CODE, STEEL_NAME) VALUES (5, '80Х', 'Сталь 80Х');
INSERT INTO HLP_STEEL_GRADE (ID_STEEL_GRADE, STEEL_CODE, STEEL_NAME) VALUES (6, '85Х', 'Сталь 85Х');

COMMIT;




INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (1, DATE '2026-07-28', 1, 312.450, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (2, DATE '2026-07-28', 2, 285.120, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (3, DATE '2026-07-28', 3, 478.330, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (4, DATE '2026-07-28', 4, 321.560, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (5, DATE '2026-07-28', 5, 298.740, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (6, DATE '2026-07-28', 6, 22.810, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (7, DATE '2026-07-28', 7, 134.290, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (8, DATE '2026-07-28', 8, 128.540, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (9, DATE '2026-07-28', 9, 142.890, 'ППБ');


INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (10, DATE '2026-07-29', 1, 298.760, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (11, DATE '2026-07-29', 2, 271.340, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (12, DATE '2026-07-29', 3, 465.880, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (13, DATE '2026-07-29', 4, 308.920, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (14, DATE '2026-07-29', 5, 287.650, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (15, DATE '2026-07-29', 6, 21.450, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (16, DATE '2026-07-29', 7, 128.970, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (17, DATE '2026-07-29', 8, 121.340, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (18, DATE '2026-07-29', 9, 135.670, 'ППБ');


INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (19, DATE '2026-07-30', 1, 305.120, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (20, DATE '2026-07-30', 5, 294.380, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (21, DATE '2026-07-31', 1, 318.900, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (22, DATE '2026-07-31', 5, 289.120, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (23, DATE '2026-08-01', 1, 302.450, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (24, DATE '2026-08-01', 5, 296.780, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (25, DATE '2026-08-02', 1, 310.670, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (26, DATE '2026-08-02', 5, 291.340, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (27, DATE '2026-08-03', 1, 295.890, 'ППБ');

INSERT INTO PRODUCTION_REPORT (ID_PRODUCTION_REPORT, REPORT_DATE, ID_PRODUCTION_SITE, PRODUCED_WEIGHT_TONNES, SOURCE_SYSTEM)
VALUES (28, DATE '2026-08-03', 5, 283.560, 'ППБ');

COMMIT;







INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    1, DATE '2026-07-28', 5, 1,  -- Участок УТВ-МК, ОТК
    0.050, NULL, 1, 1, 11,  -- Намот, Сбой укладчик -> пиноль
    'Акт Т46-2026', 20, 'К-1001', 'Пл.4521',
    1, NULL, 'СтПЦ-2', 'Стан-14',
    6, '2х0,30НТ', 1001, 1,
    '95Г2Ф', 'Стан-14', 'З-8801', 50, NULL, NULL,
    NULL, NULL  -- ещё не доработано
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    2, DATE '2026-07-28', 5, 1,
    0.030, NULL, 1, 2, 21,  -- Намот, Отсутствие контроля -> Выдан ТП
    'Акт Т46-2026', 20, 'К-1002', 'Пл.4521',
    1, NULL, 'СтПЦ-2', 'Стан-14',
    6, '2х0,30НТ', 1001, 1,
    '95Г2Ф', 'Стан-14', 'З-8801', 30, NULL, DATE '2026-07-29',
    1, 0.030  -- восстановлено
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    3, DATE '2026-07-28', 5, 3,  -- ЛИ
    0.020, NULL, 2, 2, 21,  -- Кольцо, Отсутствие контроля
    'Акт Т46-2026', 22, 'К-1003', 'Пл.4522',
    2, NULL, 'СтПЦ-2', 'Стан-15',
    7, '2х0,30НТ', 1002, 2,
    '08ГФ', 'Стан-15', 'З-8802', 20, NULL, DATE '2026-07-29',
    2, 0.020  -- переназначено
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    4, DATE '2026-07-29', 5, 1,
    0.018, NULL, 4, 4, 41,  -- Непрямолинейность, Износ роликов
    'Акт Т46-2026', 22, 'К-1004', 'Пл.4523',
    2, NULL, 'СтПЦ-2', 'Стан-15',
    7, '3+2х0,30НТ', 1003, 2,
    '08ГФ', 'Стан-15', 'З-8803', 18, NULL, DATE '2026-07-30',
    1, 0.018
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    5, DATE '2026-07-29', 5, 1,
    0.025, NULL, 1, 1, 12,  -- Намот, Сбой укладчика -> Износ ремня
    'Акт Т46-2026', 30, 'К-1005', 'Пл.4524',
    3, NULL, 'СтПЦ-2', 'Стан-16',
    10, '3+2х0,30НТ', 1004, 3,
    '95Г2Ф', 'Стан-16', 'З-8804', 25, NULL, DATE '2026-07-30',
    1, 0.025
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    6, DATE '2026-07-30', 5, 1,
    0.015, 0.015, 8, 6, 61,  -- Дефект покрытия, Технологический режим -> Температура
    'Акт Т46-2026', 20, 'К-1006', 'Пл.4525',
    1, NULL, 'СтПЦ-2', 'Стан-14',
    6, '2х0,30НТ', 1001, 1,
    '95Г2Ф', 'Стан-14', 'З-8805', 15, NULL, NULL,
    NULL, NULL
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    7, DATE '2026-07-30', 5, 5,  -- Возврат
    0.022, NULL, 1, 3, 31,  -- Намот, Разбило волоку -> Износ волок
    'Акт Т46-2026', 20, 'К-1007', 'Пл.4526',
    1, NULL, 'СтПЦ-2', 'Стан-14',
    6, '2х0,30НТ', 1001, 1,
    '95Г2Ф', 'Стан-14', 'З-8806', 22, NULL, DATE '2026-07-31',
    1, 0.022
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    8, DATE '2026-07-31', 5, 1,
    0.020, NULL, 4, 8, 81,  -- Непрямолинейность, Человеческий фактор -> Ошибочная установка
    'Акт Т46-2026', 22, 'К-1008', 'Пл.4527',
    2, NULL, 'СтПЦ-2', 'Стан-15',
    7, '3+2х0,30НТ', 1005, 2,
    '08ГФ', 'Стан-15', 'З-8807', 20, NULL, DATE '2026-08-01',
    1, 0.020
);



INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    9, DATE '2026-07-28', 8, 1,  -- КУ-1, ОТК
    0.100, NULL, 6, 2, 21,  -- Некачественная свивка, Отсутствие контроля
    'Акт Т46-2026', NULL, 'К-2001', 'Пл.5001',
    1, 'КУ-1', 'СтПЦ-2', 'Канатная-1',
    NULL, '2х0,30НТ', 2001, 1,
    '95Г2Ф', 'Канатная-1', NULL, 100, NULL, DATE '2026-07-29',
    1, 0.080
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    10, DATE '2026-07-28', 8, 3,
    0.020, NULL, 6, 5, NULL,  -- Некачественная свивка, Отсутствует ЗЧ
    'Акт Т46-2026', NULL, 'К-2002', 'Пл.5002',
    2, 'КУ-1', 'СтПЦ-2', 'Канатная-2',
    NULL, '3+2х0,30НТ', 2002, 2,
    '08ГФ', 'Канатная-2', NULL, 20, NULL, DATE '2026-07-29',
    2, 0.020
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    11, DATE '2026-07-29', 8, 1,
    0.018, 0.018, 6, 8, 82,  -- Некачественная свивка, Чел. фактор -> Неправильная сборка
    'Акт Т46-2026', NULL, 'К-2003', 'Пл.5003',
    1, 'КУ-1', 'СтПЦ-2', 'Канатная-1',
    NULL, '2х0,30НТ', 2001, 1,
    '95Г2Ф', 'Канатная-1', NULL, 18, NULL, NULL,
    NULL, NULL
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    12, DATE '2026-07-30', 8, 1,
    0.018, NULL, 7, 1, 13,  -- Сбой в укладчике -> Не установлена
    'Акт Т46-2026', NULL, 'К-2004', 'Пл.5004',
    2, 'КУ-1', 'СтПЦ-2', 'Канатная-2',
    NULL, '3+2х0,30НТ', 2003, 2,
    '08ГФ', 'Канатная-2', NULL, 18, NULL, DATE '2026-07-31',
    1, 0.018
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    13, DATE '2026-07-31', 8, 1,
    0.085, 0.085, 10, 7, 71,  -- Пересорт, Несоответствие заготовки -> Диаметр
    'Акт Т46-2026', NULL, 'К-2005', 'Пл.5005',
    1, 'КУ-1', 'СтПЦ-2', 'Канатная-1',
    NULL, '2х0,30НТ', 2001, 1,
    '95Г2Ф', 'Канатная-1', NULL, 85, NULL, NULL,
    NULL, NULL
);



INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    14, DATE '2026-07-28', 3, 1,  -- ГСВ, ОТК
    0.040, NULL, 1, 1, 11,  -- Намот
    'Акт Т46-2026', 40, 'К-3001', 'Пл.6001',
    1, 'ГСВ', 'СтПЦ-2', 'Стан-Г-1',
    12, NULL, 3001, 1,
    '65Г', 'Стан-Г-1', 'З-9001', 40, NULL, DATE '2026-07-29',
    1, 0.040
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    15, DATE '2026-07-29', 3, 2,  -- ГСВ, Цех
    0.090, NULL, 2, 2, 21,  -- Кольцо
    'Акт Т46-2026', 50, 'К-3002', 'Пл.6002',
    2, 'ГСВ', 'СтПЦ-2', 'Стан-Г-2',
    13, NULL, 3002, 2,
    '70Х', 'Стан-Г-2', 'З-9002', 90, NULL, DATE '2026-07-30',
    1, 0.090
);



INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    16, DATE '2026-07-28', 4, 1,  -- ТТГУ, ОТК
    0.285, NULL, 9, 6, 62,  -- Дефект травления, Нарушен режим -> Скорость
    'Акт Т46-2026', NULL, 'К-4001', 'Пл.7001',
    1, 'ТТГУ', 'СтПЦ-2', 'Травма-1',
    8, NULL, 4001, 1,
    '80Х', 'Травма-1', 'З-9101', 285, NULL, DATE '2026-07-29',
    1, 0.285
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    17, DATE '2026-07-30', 4, 1,
    0.050, 0.050, 8, 6, 61,  -- Дефект покрытия
    'Акт Т46-2026', NULL, 'К-4002', 'Пл.7002',
    1, 'ТТГУ', 'СтПЦ-2', 'Травма-2',
    8, NULL, 4002, 1,
    '85Х', 'Травма-2', 'З-9102', 50, NULL, NULL,
    NULL, NULL
);



INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    18, DATE '2026-07-28', 2, 1,  -- ТУ, ОТК
    0.065, NULL, 9, 6, 62,  -- Дефект травления
    'Акт Т46-2026', NULL, 'Б-1001', 'Пл.8001',
    1, 'ТУ', 'СтПЦ-2', 'Травилка-1',
    NULL, NULL, 5001, 1,
    '65Г', 'Травилка-1', NULL, 65, NULL, DATE '2026-07-29',
    1, 0.065
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    19, DATE '2026-07-29', 2, 3,  -- ТУ, ЛИ
    0.035, NULL, 8, 8, 81,  -- Дефект покрытия, Чел. фактор
    'Акт Т46-2026', NULL, 'Б-1002', 'Пл.8002',
    2, 'ТУ', 'СтПЦ-2', 'Травилка-2',
    NULL, NULL, 5002, 2,
    '70Х', 'Травилка-2', NULL, 35, NULL, DATE '2026-07-30',
    1, 0.035
);



INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    20, DATE '2026-07-28', 1, 2,  -- СК, Цех
    0.012, NULL, 1, 5, NULL,  -- Намот
    'Акт Т46-2026', NULL, 'Бунт-2001', 'Пл.3001',
    NULL, 'СК', 'СтПЦ-2', NULL,
    NULL, NULL, NULL, 1,
    '08ГФ', NULL, 12, NULL, DATE '2026-07-29',
    1, 0.012
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    21, DATE '2026-07-30', 1, 1,  -- СК, ОТК
    0.008, 0.008, 10, 7, 72,  -- Пересорт
    'Акт Т46-2026', NULL, 'Бунт-2002', 'Пл.3002',
    NULL, 'СК', 'СтПЦ-2', NULL,
    NULL, NULL, NULL, 1,
    '95Г2Ф', NULL, 8, NULL, NULL,
    NULL, NULL
);



INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    22, DATE '2026-07-28', 6, 1,  -- УТВ-РМЛ, ОТК
    0.015, NULL, 1, 1, 11,  -- Намот
    'Акт Т46-2026', 60, 'К-6001', 'Пл.9001',
    1, 'УТВ-РМЛ', 'СтПЦ-2', 'Стан-Р-1',
    14, NULL, 6001, 1,
    '65Г', 'Стан-Р-1', 'З-9201', 15, NULL, DATE '2026-07-29',
    1, 0.015
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    23, DATE '2026-07-30', 6, 1,
    0.028, NULL, 2, 3, 31,  -- Кольцо
    'Акт Т46-2026', 80, 'К-6002', 'Пл.9002',
    2, 'УТВ-РМЛ', 'СтПЦ-2', 'Стан-Р-2',
    15, NULL, 6002, 2,
    '70Х', 'Стан-Р-2', 'З-9202', 28, NULL, DATE '2026-07-31',
    1, 0.028
);



INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    24, DATE '2026-07-28', 9, 1,  -- КУ-2, ОТК
    0.120, NULL, 6, 2, 21,  -- Некачественная свивка
    'Акт Т46-2026', NULL, 'К-9001', 'Пл.1001',
    1, 'КУ-2', 'СтПЦ-2', 'Канатная-3',
    NULL, '2х0,35НТ', 9001, 1,
    '95Г2Ф', 'Канатная-3', NULL, 120, NULL, DATE '2026-07-29',
    1, 0.100
);


INSERT INTO NONCONFORMING_PRODUCT (
    ID_NONCONFORMING_PRODUCT, DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    25, DATE '2026-07-31', 9, 1,
    0.065, 0.065, 10, 7, 71,  -- Пересорт
    'Акт Т46-2026', NULL, 'К-9002', 'Пл.1002',
    2, 'КУ-2', 'СтПЦ-2', 'Канатная-4',
    NULL, '3+2х0,35НТ', 9002, 2,
    '08ГФ', 'Канатная-4', NULL, 65, NULL, NULL,
    NULL, NULL
);

COMMIT;





ALTER SEQUENCE SEQ_HLP_PRODUCTION_SITE INCREMENT BY 1 NOCACHE;
ALTER SEQUENCE SEQ_HLP_DEFECT_TYPE INCREMENT BY 1 NOCACHE;
ALTER SEQUENCE SEQ_HLP_DEFECT_CAUSE INCREMENT BY 1 NOCACHE;
ALTER SEQUENCE SEQ_HLP_DETECTION_SOURCE INCREMENT BY 1 NOCACHE;
ALTER SEQUENCE SEQ_HLP_REWORK_TYPE INCREMENT BY 1 NOCACHE;
ALTER SEQUENCE SEQ_HLP_DIAMETER INCREMENT BY 1 NOCACHE;
ALTER SEQUENCE SEQ_HLP_STEEL_GRADE INCREMENT BY 1 NOCACHE;
ALTER SEQUENCE SEQ_NONCONFORMING_PRODUCT INCREMENT BY 1 NOCACHE;
ALTER SEQUENCE SEQ_PRODUCTION_REPORT INCREMENT BY 1 NOCACHE;

COMMIT;




























