




DELETE FROM NONCONFORMING_PRODUCT;
DELETE FROM PRODUCTION_REPORT WHERE ID_PRODUCTION_REPORT > 27;

COMMIT;


ALTER SEQUENCE SEQ_NONCONFORMING_PRODUCT RESTART START WITH 100;
ALTER SEQUENCE SEQ_PRODUCTION_REPORT RESTART START WITH 30;

COMMIT;


SELECT 'NONCONFORMING_PRODUCT rows: ' || COUNT(*) FROM NONCONFORMING_PRODUCT;
/
