INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-28', 5, 1,  -- УТВ_МК, ОТК
    0.050, NULL, 1, 1, 11,  -- Намот, Сбой укладчик -> IZNOS_VOLOKI
    'Акт Т46-2026 №1', 20, 'К-1001', 'Пл.4521',
    1, NULL, 'СтПЦ-2', 'Стан-14',
    724, '2х0,30НТ', 1001, 1,
    '4', 'Стан-14', 'З-8801', 50, NULL, NULL,
    NULL, NULL  -- ещё не доработано
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-28', 5, 1,
    0.030, NULL, 1, 2, 41,  -- Намот, Отсутствует контроль -> OTSUST_KONTROL
    'Акт Т46-2026 №2', 20, 'К-1002', 'Пл.4521',
    1, NULL, 'СтПЦ-2', 'Стан-14',
    724, '2х0,30НТ', 1001, 1,
    '4', 'Стан-14', 'З-8801', 30, NULL, DATE '2026-07-29',
    1, 0.030  -- восстановлено
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-28', 5, 3,  -- ЛИ
    0.020, NULL, 2, 2, 41,  -- Кольцо, Отсутствует контроль
    'Акт Т46-2026 №3', 22, 'К-1003', 'Пл.4522',
    2, NULL, 'СтПЦ-2', 'Стан-15',
    725, '2х0,30НТ', 1002, 2,
    '4', 'Стан-15', 'З-8802', 20, NULL, DATE '2026-07-29',
    2, 0.020  -- переназначено
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-29', 5, 1,
    0.018, NULL, 4, 4, 41,  -- Непрямолинейность, Износ роликов
    'Акт Т46-2026 №4', 22, 'К-1004', 'Пл.4523',
    2, NULL, 'СтПЦ-2', 'Стан-15',
    725, '3+2х0,30НТ', 1003, 2,
    '4', 'Стан-15', 'З-8803', 18, NULL, DATE '2026-07-30',
    1, 0.018
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-29', 5, 1,
    0.025, NULL, 1, 1, 12,  -- Намот, Сбой укладчик -> NEPR_MONTAZH
    'Акт Т46-2026 №5', 30, 'К-1005', 'Пл.4524',
    3, NULL, 'СтПЦ-2', 'Стан-16',
    730, '3+2х0,30НТ', 1004, 3,
    '4', 'Стан-16', 'З-8804', 25, NULL, DATE '2026-07-30',
    1, 0.025
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-30', 5, 1,
    0.015, 0.015, 8, 6, 61,  -- Дефект покрытия, Нарушен режим -> NEKACH_SMAZKA
    'Акт Т46-2026 №6', 20, 'К-1006', 'Пл.4525',
    1, NULL, 'СтПЦ-2', 'Стан-14',
    724, '2х0,30НТ', 1001, 1,
    '4', 'Стан-14', 'З-8805', 15, NULL, NULL,
    NULL, NULL
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-30', 5, 4,  -- ЦЗЛ
    0.022, NULL, 1, 3, 13,  -- Намот, Разбило чистовую -> NESOOTV_VOLOKI
    'Акт Т46-2026 №7', 20, 'К-1007', 'Пл.4526',
    1, NULL, 'СтПЦ-2', 'Стан-14',
    724, '2х0,30НТ', 1001, 1,
    '4', 'Стан-14', 'З-8806', 22, NULL, DATE '2026-07-31',
    1, 0.022
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-31', 5, 1,
    0.020, NULL, 4, 8, 82,  -- Непрямолинейность, Чел. фактор -> Неправильная сборка
    'Акт Т46-2026 №8', 22, 'К-1008', 'Пл.4527',
    2, NULL, 'СтПЦ-2', 'Стан-15',
    725, '3+2х0,30НТ', 1005, 2,
    '4', 'Стан-15', 'З-8807', 20, NULL, DATE '2026-08-01',
    1, 0.020
);






INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-28', 8, 1,  -- КУ-1, ОТК
    0.100, NULL, 6, 2, 41,  -- KRZ, Отсутствует контроль
    'Акт Т46-2026 №9', NULL, 'К-2001', 'Пл.5001',
    1, 'КУ-1', 'СтПЦ-2', 'Канатная-1',
    NULL, '2х0,30НТ', 2001, 1,
    '4', 'Канатная-1', NULL, 100, NULL, DATE '2026-07-29',
    1, 0.080
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-28', 8, 3,  -- ЛИ
    0.020, NULL, 6, 5, NULL,  -- KRZ, Отсутствует ЗЧ
    'Акт Т46-2026 №10', NULL, 'К-2002', 'Пл.5002',
    2, 'КУ-1', 'СтПЦ-2', 'Канатная-2',
    NULL, '3+2х0,30НТ', 2002, 2,
    '4', 'Канатная-2', NULL, 20, NULL, DATE '2026-07-29',
    2, 0.020
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-29', 8, 1,
    0.018, 0.018, 11, 8, 82,  -- Брак неисправимый, Чел. фактор
    'Акт Т46-2026 №11', NULL, 'К-2003', 'Пл.5003',
    1, 'КУ-1', 'СтПЦ-2', 'Канатная-1',
    NULL, '2х0,30НТ', 2001, 1,
    '4', 'Канатная-1', NULL, 18, NULL, NULL,
    NULL, NULL
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-30', 8, 1,
    0.018, NULL, 7, 1, 12,  -- Сбой укладчик, NEPR_MONTAZH
    'Акт Т46-2026 №12', NULL, 'К-2004', 'Пл.5004',
    2, 'КУ-1', 'СтПЦ-2', 'Канатная-2',
    NULL, '3+2х0,30НТ', 2003, 2,
    '4', 'Канатная-2', NULL, 18, NULL, DATE '2026-07-31',
    1, 0.018
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-31', 8, 1,
    0.085, 0.085, 10, 7, 71,  -- Пересорт, Несоответствие заготовки -> Диаметр
    'Акт Т46-2026 №13', NULL, 'К-2005', 'Пл.5005',
    1, 'КУ-1', 'СтПЦ-2', 'Канатная-1',
    NULL, '2х0,30НТ', 2001, 1,
    '4', 'Канатная-1', NULL, 85, NULL, NULL,
    NULL, NULL
);






INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-28', 3, 1,  -- ГСВ, ОТК
    0.040, NULL, 1, 1, 11,  -- Намот, IZNOS_VOLOKI
    'Акт Т46-2026 №14', 40, 'К-3001', 'Пл.6001',
    1, 'ГСВ', 'СтПЦ-2', 'Стан-Г-1',
    733, NULL, 3001, 1,
    '16', 'Стан-Г-1', 'З-9001', 40, NULL, DATE '2026-07-29',
    1, 0.040
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-29', 3, 2,  -- ГСВ, Цех
    0.090, NULL, 2, 2, 41,  -- Кольцо, OTSUST_KONTROL
    'Акт Т46-2026 №15', 50, 'К-3002', 'Пл.6002',
    2, 'ГСВ', 'СтПЦ-2', 'Стан-Г-2',
    736, NULL, 3002, 2,
    '16', 'Стан-Г-2', 'З-9002', 90, NULL, DATE '2026-07-30',
    1, 0.090
);






INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-28', 4, 1,  -- ТТГУ, ОТК
    0.285, NULL, 9, 6, 61,  -- Дефект травления, NEKACH_SMAZKA
    'Акт Т46-2026 №16', NULL, 'К-4001', 'Пл.7001',
    1, 'ТТГУ', 'СтПЦ-2', 'Травма-1',
    724, NULL, 4001, 1,
    '16', 'Травма-1', 'З-9101', 285, NULL, DATE '2026-07-29',
    1, 0.285
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-30', 4, 1,
    0.050, 0.050, 8, 6, 61,  -- Дефект покрытия
    'Акт Т46-2026 №17', NULL, 'К-4002', 'Пл.7002',
    1, 'ТТГУ', 'СтПЦ-2', 'Травма-2',
    724, NULL, 4002, 1,
    '16', 'Травма-2', 'З-9102', 50, NULL, NULL,
    NULL, NULL
);






INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-28', 2, 1,  -- ТУ, ОТК
    0.065, NULL, 9, 6, 61,  -- Дефект травления
    'Акт Т46-2026 №18', NULL, 'Б-1001', 'Пл.8001',
    1, 'ТУ', 'СтПЦ-2', 'Травилка-1',
    NULL, NULL, 5001, 1,
    '16', 'Травилка-1', NULL, 65, NULL, DATE '2026-07-29',
    1, 0.065
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-29', 2, 3,  -- ТУ, ЛИ
    0.035, NULL, 8, 8, 82,  -- Дефект покрытия, Чел. фактор
    'Акт Т46-2026 №19', NULL, 'Б-1002', 'Пл.8002',
    2, 'ТУ', 'СтПЦ-2', 'Травилка-2',
    NULL, NULL, 5002, 2,
    '16', 'Травилка-2', NULL, 35, NULL, DATE '2026-07-30',
    1, 0.035
);






INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-28', 1, 2,  -- СК, Цех
    0.012, NULL, 1, 5, NULL,  -- Намот, Отсутствует ЗЧ
    'Акт Т46-2026 №20', NULL, 'Бунт-2001', 'Пл.3001',
    NULL, 'СК', 'СтПЦ-2', NULL,
    NULL, NULL, NULL, 1,
    '16', NULL, 12, NULL, DATE '2026-07-29',
    1, 0.012
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-30', 1, 1,  -- СК, ОТК
    0.008, 0.008, 10, 7, 52,  -- Пересорт, Несоответствие марки
    'Акт Т46-2026 №21', NULL, 'Бунт-2002', 'Пл.3002',
    NULL, 'СК', 'СтПЦ-2', NULL,
    NULL, NULL, NULL, 1,
    '16', NULL, 8, NULL, NULL,
    NULL, NULL
);






INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-28', 6, 1,  -- УТВ_РМЛ, ОТК
    0.015, NULL, 1, 1, 11,  -- Намот
    'Акт Т46-2026 №22', 60, 'К-6001', 'Пл.9001',
    1, 'УТВ-РМЛ', 'СтПЦ-2', 'Стан-Р-1',
    736, NULL, 6001, 1,
    '16', 'Стан-Р-1', 'З-9201', 15, NULL, DATE '2026-07-29',
    1, 0.015
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-30', 6, 1,
    0.028, NULL, 2, 3, 11,  -- Кольцо, IZNOS_VOLOKI
    'Акт Т46-2026 №23', 80, 'К-6002', 'Пл.9002',
    2, 'УТВ-РМЛ', 'СтПЦ-2', 'Стан-Р-2',
    423, NULL, 6002, 2,
    '16', 'Стан-Р-2', 'З-9202', 28, NULL, DATE '2026-07-31',
    1, 0.028
);






INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-28', 9, 1,  -- КУ-2, ОТК
    0.120, NULL, 6, 2, 41,  -- KRZ, OTSUST_KONTROL
    'Акт Т46-2026 №24', NULL, 'К-9001', 'Пл.1001',
    1, 'КУ-2', 'СтПЦ-2', 'Канатная-3',
    NULL, '2х0,35НТ', 9001, 1,
    '4', 'Канатная-3', NULL, 120, NULL, DATE '2026-07-29',
    1, 0.100
);


INSERT INTO NONCONFORMING_PRODUCT (
    DETECTION_DATE, ID_PRODUCTION_SITE, ID_DETECTION_SOURCE,
    WEIGHT_TONNES, IRREPARABLE_WEIGHT_TONNES, ID_DEFECT_TYPE, ID_DEFECT_CAUSE,
    ID_DEFECT_SUBCAUSE, NOTE, PRODUCT_CODE, REEL_NUMBER, HEAT_NUMBER,
    MANUFACTURER_BRIGADE, BUNDLE_NUMBER, MANUFACTURER_WORKSHOP, EQUIPMENT_KEY,
    ID_DIAMETER, STEEL_CORD_CONSTRUCTION, OPERATOR_PERSONAL_NUMBER, BRIGADE,
    STEEL_GRADE, UNIT_NUMBER, WORKPIECE_KEY, QUANTITY, REWORK_QUANTITY, REWORK_DATE,
    ID_REWORK_TYPE, REWORK_WEIGHT_TONNES
) VALUES (
    DATE '2026-07-31', 9, 1,
    0.065, 0.065, 10, 7, 71,  -- Пересорт, Несоответствие диаметра
    'Акт Т46-2026 №25', NULL, 'К-9002', 'Пл.1002',
    2, 'КУ-2', 'СтПЦ-2', 'Канатная-4',
    NULL, '3+2х0,35НТ', 9002, 2,
    '4', 'Канатная-4', NULL, 65, NULL, NULL,
    NULL, NULL
);

COMMIT;




SELECT '=== Проверка: записей всего ===' FROM DUAL;
SELECT COUNT(*) AS TOTAL_RECORDS FROM NONCONFORMING_PRODUCT;

SELECT '=== Проверка: по участкам ===' FROM DUAL;
SELECT ps.SITE_CODE, ps.SITE_NAME, COUNT(n.ID_NONCONFORMING_PRODUCT) AS CNT,
       SUM(n.WEIGHT_TONNES) AS TOTAL_WEIGHT
FROM NONCONFORMING_PRODUCT n
JOIN HLP_PRODUCTION_SITE ps ON n.ID_PRODUCTION_SITE = ps.ID_PRODUCTION_SITE
GROUP BY ps.SITE_CODE, ps.SITE_NAME
ORDER BY ps.SITE_CODE;

SELECT '=== Проверка: по видам дефектов ===' FROM DUAL;
SELECT dt.DEFECT_NAME, SUM(n.WEIGHT_TONNES) AS TOTAL_WEIGHT,
       SUM(CASE WHEN n.REWORK_DATE IS NOT NULL THEN 1 ELSE 0 END) AS REWORKED_COUNT
FROM NONCONFORMING_PRODUCT n
JOIN HLP_DEFECT_TYPE dt ON n.ID_DEFECT_TYPE = dt.ID_DEFECT_TYPE
GROUP BY dt.DEFECT_NAME
ORDER BY TOTAL_WEIGHT DESC;

SELECT '=== Проверка: общая масса ===' FROM DUAL;
SELECT SUM(WEIGHT_TONNES) AS TOTAL_WEIGHT,
       SUM(IRREPARABLE_WEIGHT_TONNES) AS TOTAL_IRREPARABLE,
       SUM(REWORK_WEIGHT_TONNES) AS TOTAL_REWORKED
FROM NONCONFORMING_PRODUCT;
